# Generated by Django 2.0 on 2018-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30, unique=True, verbose_name='структурное подразделение')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
            },
        ),
        migrations.AlterField(
            model_name='measure',
            name='key',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='national_symbol',
            field=models.CharField(max_length=15, unique=True, verbose_name='национальное условное обозначение'),
        ),
    ]
