# Generated by Django 2.0 on 2018-06-01 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdog', '0002_auto_20180528_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('store_place_id', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='категория')),
                ('store_place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hdog.Measure', verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'ТМЦ',
                'verbose_name_plural': 'ТМЦ',
            },
        ),
        migrations.CreateModel(
            name='InventoryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='инвентарный номер')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_numbers', to='hdog.Goods')),
            ],
            options={
                'verbose_name': 'инвентарный номер',
                'verbose_name_plural': 'инвентарные номера',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='фамилия')),
                ('forename', models.CharField(max_length=20, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='отчество')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата')),
                ('number', models.PositiveSmallIntegerField(verbose_name='номер')),
                ('comment', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'перемещение',
                'verbose_name_plural': 'перемещения',
            },
        ),
        migrations.CreateModel(
            name='TransferedGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('inv_numbers', models.ManyToManyField(to='hdog.InventoryNumber', verbose_name='инвентарные номера')),
                ('recepient_goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_goods', to='hdog.Goods', verbose_name='ТМЦ получателя')),
                ('sender_goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_goods', to='hdog.Goods', verbose_name='ТМЦ отправителя')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='hdog.Transfer', verbose_name='перемещение')),
            ],
            options={
                'verbose_name': 'перемещенные ТМЦ',
                'verbose_name_plural': 'перемещенные ТМЦ',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='вид деятельности'),
        ),
        migrations.AlterUniqueTogether(
            name='goods',
            unique_together={('name', 'store_place_type', 'store_place_id')},
        ),
    ]
