# Generated by Django 2.0 on 2018-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdog', '0007_auto_20180615_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
    ]
