# Generated by Django 2.0 on 2018-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdog', '0008_auto_20181016_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferedgoods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='цена'),
        ),
    ]
